CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_make VARCHAR(30) NOT NULL,
    inv_model VARCHAR(30) NOT NULL,
    inv_year INT NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR(50) NOT NULL,
    inv_thumbnail VARCHAR(50) NOT NULL,
    inv_price NUMERIC(9,2) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color VARCHAR(20) NOT NULL,
    classification_id INT NOT NULL REFERENCES public.classification(classification_id)
);